<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-09-15 18:31

$extensionPath = TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('solr');
return array(

		// SolrPhpClient

	'apache_solr_httptransport_abstract' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/HttpTransport/Abstract.php',
	'apache_solr_httptransport_curl' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/HttpTransport/Curl.php',
	'apache_solr_httptransport_curlnoreuse' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/HttpTransport/CurlNoReuse.php',
	'apache_solr_httptransport_filegetcontents' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/HttpTransport/FileGetContents.php',
	'apache_solr_httptransport_interface' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/HttpTransport/Interface.php',
	'apache_solr_httptransport_response' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/HttpTransport/Response.php',
	'apache_solr_service_balancer' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/Service/Balancer.php',
	'apache_solr_document' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/Document.php',
	'apache_solr_exception' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/Exception.php',
	'apache_solr_httptransportexception' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/HttpTransportException.php',
	'apache_solr_invalidargumentexception' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/InvalidArgumentException.php',
	'apache_solr_noserviceavailableexception' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/NoServiceAvailableException.php',
	'apache_solr_parserexception' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/ParserException.php',
	'apache_solr_response' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/Response.php',
	'apache_solr_service' => $extensionPath . 'Lib/SolrPhpClient/Apache/Solr/Service.php',

	// EXT:solr

	'Tx_Solr_Api' => $extensionPath . 'Classes/Api.php',
	'Tx_Solr_Additionalfieldsindexer' => $extensionPath . 'Classes/AdditionalFieldsIndexer.php',
	'Tx_Solr_Commandresolver' => $extensionPath . 'Classes/CommandResolver.php',
	'Tx_Solr_Connectionmanager' => $extensionPath . 'Classes/ConnectionManager.php',
	'Tx_Solr_Contextmenuactioncontroller' => $extensionPath . 'Classes/ContextMenuActionController.php',
	'Tx_Solr_Databaseutility' => $extensionPath . 'Classes/DatabaseUtility.php',
	'Tx_Solr_Garbagecollector' => $extensionPath . 'Classes/GarbageCollector.php',
	'Tx_Solr_Htmlcontentextractor' => $extensionPath . 'Classes/HtmlContentExtractor.php',
	'Tx_Solr_Javascriptmanager' => $extensionPath . 'Classes/JavascriptManager.php',
	'Tx_Solr_Languagefileunavailableexception' => $extensionPath . 'Classes/LanguageFileUnavailableException.php',
	'Tx_Solr_Nosolrconnectionfoundexception' => $extensionPath . 'Classes/NoSolrConnectionFoundException.php',
	'Tx_Solr_Query' => $extensionPath . 'Classes/Query.php',
	'Tx_Solr_Search' => $extensionPath . 'Classes/Search.php',
	'Tx_Solr_Site' => $extensionPath . 'Classes/Site.php',
	'Tx_Solr_Solrservice' => $extensionPath . 'Classes/SolrService.php',
	'Tx_Solr_Sorting' => $extensionPath . 'Classes/Sorting.php',
	'Tx_Solr_Spellchecker' => $extensionPath . 'Classes/SpellChecker.php',
	'Tx_Solr_Suggestquery' => $extensionPath . 'Classes/SuggestQuery.php',
	'Tx_Solr_Template' => $extensionPath . 'Classes/Template.php',
	'Tx_Solr_Typo3environment' => $extensionPath . 'Classes/Typo3Environment.php',
	'Tx_Solr_Typo3pagecontentextractor' => $extensionPath . 'Classes/Typo3PageContentExtractor.php',
	'Tx_Solr_Typo3pageindexer' => $extensionPath . 'Classes/Typo3PageIndexer.php',
	'Tx_Solr_Util' => $extensionPath . 'Classes/Util.php',

	'Tx_Solr_Access_Rootline' => $extensionPath . 'Classes/Access/Rootline.php',
	'Tx_Solr_Access_Rootlineelement' => $extensionPath . 'Classes/Access/RootlineElement.php',
	'Tx_Solr_Access_Rootlineelementformatexception' => $extensionPath . 'Classes/Access/RootlineElementFormatException.php',

	'Tx_Solr_Backend_Indexingconfigurationselectorfield' => $extensionPath . 'Classes/Backend/IndexingConfigurationSelectorField.php',

	'Tx_Solr_Cli_Dispatcher' => $extensionPath . 'Classes/Cli/Dispatcher.php',

	'Tx_Solr_Contentobject_Content' => $extensionPath . 'Classes/ContentObject/Content.php',
	'Tx_Solr_Contentobject_Multivalue' => $extensionPath . 'Classes/ContentObject/Multivalue.php',
	'Tx_Solr_Contentobject_Relation' => $extensionPath . 'Classes/ContentObject/Relation.php',

	'Tx_Solr_Facet_Abstractfacetrenderer' => $extensionPath . 'Classes/Facet/AbstractFacetRenderer.php',
	'Tx_Solr_Facet_Daterangefacetrenderer' => $extensionPath . 'Classes/Facet/DateRangeFacetRenderer.php',
	'Tx_Solr_Facet_Facet' => $extensionPath . 'Classes/Facet/Facet.php',
	'Tx_Solr_Facet_Facetoption' => $extensionPath . 'Classes/Facet/FacetOption.php',
	'Tx_Solr_Facet_Facetrendererfactory' => $extensionPath . 'Classes/Facet/FacetRendererFactory.php',
	'Tx_Solr_Facet_Hierarchicalfacetrenderer' => $extensionPath . 'Classes/Facet/HierarchicalFacetRenderer.php',
	'Tx_Solr_Facet_Hierarchicalfacethelper' => $extensionPath . 'Classes/Facet/HierarchicalFacetHelper.php',
	'Tx_Solr_Facet_Linkbuilder' => $extensionPath . 'Classes/Facet/LinkBuilder.php',
	'Tx_Solr_Facet_Numericrangefacetrenderer' => $extensionPath . 'Classes/Facet/NumericRangeFacetRenderer.php',
	'Tx_Solr_Facet_Querygroupfacetrenderer' => $extensionPath . 'Classes/Facet/QueryGroupFacetRenderer.php',
	'Tx_Solr_Facet_Simplefacetrenderer' => $extensionPath . 'Classes/Facet/SimpleFacetRenderer.php',
	'Tx_Solr_Facet_Simplefacetoptionsrenderer' => $extensionPath . 'Classes/Facet/SimpleFacetOptionsRenderer.php',
	'Tx_Solr_Facet_Usedfacetrenderer' => $extensionPath . 'Classes/Facet/UsedFacetRenderer.php',

	'Tx_Solr_Fieldprocessor_Abstracthierarchyprocessor' => $extensionPath . 'Classes/FieldProcessor/AbstractHierarchyProcessor.php',
	'Tx_Solr_Fieldprocessor_Categoryuidtohierarchy' => $extensionPath . 'Classes/FieldProcessor/CategoryUidToHierarchy.php',
	'Tx_Solr_Fieldprocessor_Pageuidtohierarchy' => $extensionPath . 'Classes/FieldProcessor/PageUidToHierarchy.php',
	'Tx_Solr_Fieldprocessor_Pathtohierarchy' => $extensionPath . 'Classes/FieldProcessor/PathToHierarchy.php',
	'Tx_Solr_Fieldprocessor_Service' => $extensionPath . 'Classes/FieldProcessor/Service.php',
	'Tx_Solr_Fieldprocessor_Timestamptoisodate' => $extensionPath . 'Classes/FieldProcessor/TimestampToIsoDate.php',

	'Tx_Solr_Indexqueue_Abstractindexer' => $extensionPath . 'Classes/IndexQueue/AbstractIndexer.php',
	'Tx_Solr_Indexqueue_Indexer' => $extensionPath . 'Classes/IndexQueue/Indexer.php',
	'Tx_Solr_Indexqueue_Item' => $extensionPath . 'Classes/IndexQueue/Item.php',
	'Tx_Solr_Indexqueue_Pageindexer' => $extensionPath . 'Classes/IndexQueue/PageIndexer.php',
	'Tx_Solr_Indexqueue_Pageindexerrequest' => $extensionPath . 'Classes/IndexQueue/PageIndexerRequest.php',
	'Tx_Solr_Indexqueue_Pageindexerrequesthandler' => $extensionPath . 'Classes/IndexQueue/PageIndexerRequestHandler.php',
	'Tx_Solr_Indexqueue_Pageindexerresponse' => $extensionPath . 'Classes/IndexQueue/PageIndexerResponse.php',
	'Tx_Solr_Indexqueue_Queue' => $extensionPath . 'Classes/IndexQueue/Queue.php',
	'Tx_Solr_Indexqueue_Recordmonitor' => $extensionPath . 'Classes/IndexQueue/RecordMonitor.php',

	'Tx_Solr_Indexqueue_Frontendhelper_Abstract' => $extensionPath . 'Classes/IndexQueue/FrontendHelper/Abstract.php',
	'Tx_Solr_Indexqueue_Frontendhelper_Authorizationservice' => $extensionPath . 'Classes/IndexQueue/FrontendHelper/AuthorizationService.php',
	'Tx_Solr_Indexqueue_Frontendhelper_Dispatcher' => $extensionPath . 'Classes/IndexQueue/FrontendHelper/Dispatcher.php',
	'Tx_Solr_Indexqueue_Frontendhelper_Manager' => $extensionPath . 'Classes/IndexQueue/FrontendHelper/Manager.php',
	'Tx_Solr_Indexqueue_Frontendhelper_Usergroupdetector' => $extensionPath . 'Classes/IndexQueue/FrontendHelper/UserGroupDetector.php',
	'Tx_Solr_Indexqueue_Frontendhelper_Pagefieldmappingindexer' => $extensionPath . 'Classes/IndexQueue/FrontendHelper/PageFieldMappingIndexer.php',
	'Tx_Solr_Indexqueue_Frontendhelper_Pageindexer' => $extensionPath . 'Classes/IndexQueue/FrontendHelper/PageIndexer.php',

	'Tx_Solr_Indexqueue_Initializer_Abstract' => $extensionPath . 'Classes/IndexQueue/Initializer/Abstract.php',
	'Tx_Solr_Indexqueue_Initializer_Page' => $extensionPath . 'Classes/IndexQueue/Initializer/Page.php',
	'Tx_Solr_Indexqueue_Initializer_Record' => $extensionPath . 'Classes/IndexQueue/Initializer/Record.php',

	'Tx_Solr_Pluginbase_Backendsummary' => $extensionPath . 'Classes/PluginBase/BackendSummary.php',
	'Tx_Solr_Pluginbase_Commandpluginbase' => $extensionPath . 'Classes/PluginBase/CommandPluginBase.php',
	'Tx_Solr_Pluginbase_Pluginbase' => $extensionPath . 'Classes/PluginBase/PluginBase.php',

	'Tx_Solr_Query_Linkbuilder' => $extensionPath . 'Classes/Query/LinkBuilder.php',

	'Tx_Solr_Query_Filterencoder_Daterange' => $extensionPath . 'Classes/Query/FilterEncoder/DateRange.php',
	'Tx_Solr_Query_Filterencoder_Hierarchy' => $extensionPath . 'Classes/Query/FilterEncoder/Hierarchy.php',
	'Tx_Solr_Query_Filterencoder_Querygroup' => $extensionPath . 'Classes/Query/FilterEncoder/QueryGroup.php',
	'Tx_Solr_Query_Filterencoder_Range' => $extensionPath . 'Classes/Query/FilterEncoder/Range.php',

	'Tx_Solr_Query_Modifier_Elevation' => $extensionPath . 'Classes/Query/Modifier/Elevation.php',
	'Tx_Solr_Query_Modifier_Faceting' => $extensionPath . 'Classes/Query/Modifier/Faceting.php',
	'Tx_Solr_Query_Modifier_Statistics' => $extensionPath . 'Classes/Query/Modifier/Statistics.php',

	'Tx_Solr_Response_Processor_Statisticswriter' => $extensionPath . 'Classes/Response/Processor/StatisticsWriter.php',

	'Tx_Solr_Resultdocumentmodifier_Scoreanalyzer' => $extensionPath . 'Classes/ResultDocumentModifier/ScoreAnalyzer.php',
	'Tx_Solr_Resultdocumentmodifier_Sitehighlighter' => $extensionPath . 'Classes/ResultDocumentModifier/SiteHighlighter.php',

	'Tx_Solr_Resultsetmodifier_Lastsearches' => $extensionPath . 'Classes/ResultsetModifier/LastSearches.php',

	'Tx_Solr_Search_Abstractcomponent' => $extensionPath . 'Classes/Search/AbstractComponent.php',
	'Tx_Solr_Search_Accesscomponent' => $extensionPath . 'Classes/Search/AccessComponent.php',
	'Tx_Solr_Search_Analysiscomponent' => $extensionPath . 'Classes/Search/AnalysisComponent.php',
	'Tx_Solr_Search_Debugcomponent' => $extensionPath . 'Classes/Search/DebugComponent.php',
	'Tx_Solr_Search_Elevationcomponent' => $extensionPath . 'Classes/Search/ElevationComponent.php',
	'Tx_Solr_Search_Facetingcomponent' => $extensionPath . 'Classes/Search/FacetingComponent.php',
	'Tx_Solr_Search_Highlightingcomponent' => $extensionPath . 'Classes/Search/HighlightingComponent.php',
	'Tx_Solr_Search_Lastsearchescomponent' => $extensionPath . 'Classes/Search/LastSearchesComponent.php',
	'Tx_Solr_Search_Relevancecomponent' => $extensionPath . 'Classes/Search/RelevanceComponent.php',
	'Tx_Solr_Search_SearchComponentManager' => $extensionPath . 'Classes/Search/SearchComponentManager.php',
	'Tx_Solr_Search_Sortingcomponent' => $extensionPath . 'Classes/Search/SortingComponent.php',
	'Tx_Solr_Search_Spellcheckingcomponent' => $extensionPath . 'Classes/Search/SpellcheckingComponent.php',
	'Tx_Solr_Search_Statisticscomponent' => $extensionPath . 'Classes/Search/StatisticsComponent.php',

	'Tx_Solr_Viewhelper_Abstractsubpartviewhelper' => $extensionPath . 'Classes/ViewHelper/AbstractSubpartViewHelper.php',
	'Tx_Solr_Viewhelper_Crop' => $extensionPath . 'Classes/ViewHelper/Crop.php',
	'Tx_Solr_Viewhelper_Currentresultnumber' => $extensionPath . 'Classes/ViewHelper/CurrentResultNumber.php',
	'Tx_Solr_Viewhelper_Date' => $extensionPath . 'Classes/ViewHelper/Date.php',
	'Tx_Solr_Viewhelper_Facet' => $extensionPath . 'Classes/ViewHelper/Facet.php',
	'Tx_Solr_Viewhelper_Link' => $extensionPath . 'Classes/ViewHelper/Link.php',
	'Tx_Solr_Viewhelper_Lll' => $extensionPath . 'Classes/ViewHelper/Lll.php',
	'Tx_Solr_Viewhelper_Multivalue' => $extensionPath . 'Classes/ViewHelper/Multivalue.php',
	'Tx_Solr_Viewhelper_Oddeven' => $extensionPath . 'Classes/ViewHelper/OddEven.php',
	'Tx_Solr_Viewhelper_Relevance' => $extensionPath . 'Classes/ViewHelper/Relevance.php',
	'Tx_Solr_Viewhelper_Relevancebar' => $extensionPath . 'Classes/ViewHelper/RelevanceBar.php',
	'Tx_Solr_Viewhelper_Solrlink' => $extensionPath . 'Classes/ViewHelper/SolrLink.php',
	'Tx_Solr_Viewhelper_Sortindicator' => $extensionPath . 'Classes/ViewHelper/SortIndicator.php',
	'Tx_Solr_Viewhelper_Sorturl' => $extensionPath . 'Classes/ViewHelper/SortUrl.php',
	'Tx_Solr_Viewhelper_Ts' => $extensionPath . 'Classes/ViewHelper/Ts.php',

	// modules

	'Tx_Solr_Moduleadmin' => $extensionPath . 'ModAdmin/index.php',

	'Tx_Solr_Modindex_Indexinspector' => $extensionPath . 'ModIndex/IndexInspector.php',
	'Tx_Solr_Modindex_Indexinspectorremotecontroller' => $extensionPath . 'ModIndex/IndexInspectorRemoteController.php',

	// plugins

	'Tx_Solr_Pifrequentsearches_Frequentsearches' => $extensionPath . 'PiFrequentSearches/FrequentSearches.php',
	'Tx_Solr_Piresults_Results' => $extensionPath . 'PiResults/Results.php',
	'Tx_Solr_Pisearch_Search' => $extensionPath . 'PiSearch/Search.php',

	// TYPO3 4.5
	'Tx_Solr_Pi_Frequentsearches' => $extensionPath . 'Compat/class.Tx_Solr_Pi_Frequentsearches.php',
	'Tx_Solr_Pi_Results' => $extensionPath . 'Compat/class.Tx_Solr_Pi_Results.php',
	'Tx_Solr_Pi_Search' => $extensionPath . 'Compat/class.Tx_Solr_Pi_Search.php',

	'Tx_Solr_Piresults_Advancedformcommand' => $extensionPath . 'PiResults/AdvancedFormCommand.php',
	'Tx_Solr_Piresults_Errorscommand' => $extensionPath . 'PiResults/ErrorsCommand.php',
	'Tx_Solr_Piresults_Facetingcommand' => $extensionPath . 'PiResults/FacetingCommand.php',
	'Tx_Solr_Piresults_Formcommand' => $extensionPath . 'PiResults/FormCommand.php',
	'Tx_Solr_Piresults_Frequentsearchescommand' => $extensionPath . 'PiResults/FrequentSearchesCommand.php',
	'Tx_Solr_Piresults_Highlightingresultdocumentmodifier' => $extensionPath . 'PiResults/HighlightingResultDocumentModifier.php',
	'Tx_Solr_Piresults_Lastsearchescommand' => $extensionPath . 'PiResults/LastSearchesCommand.php',
	'Tx_Solr_Piresults_Noresultscommand' => $extensionPath . 'PiResults/NoResultsCommand.php',
	'Tx_Solr_Piresults_Resultscommand' => $extensionPath . 'PiResults/ResultsCommand.php',
	'Tx_Solr_Piresults_Resultsperpageswitchcommand' => $extensionPath . 'PiResults/ResultsPerPageSwitchCommand.php',
	'Tx_Solr_Piresults_Sortingcommand' => $extensionPath . 'PiResults/SortingCommand.php',

	'Tx_Solr_Piresults_Parameterkeepingformmodifier' => $extensionPath . 'PiResults/ParameterKeepingFormModifier.php',
	'Tx_Solr_Piresults_Spellcheckformmodifier' => $extensionPath . 'PiResults/SpellCheckFormModifier.php',
	'Tx_Solr_Piresults_Suggestformmodifier' => $extensionPath . 'PiResults/SuggestFormModifier.php',
	'Tx_Solr_Piresults_Queryanalyzerformmodifier' => $extensionPath . 'PiResults/QueryAnalyzerFormModifier.php',

	// scheduler tasks

	'Tx_Solr_Scheduler_Indexqueueworkertask' => $extensionPath . 'Scheduler/IndexQueueWorkerTask.php',
	'Tx_Solr_Scheduler_Indexqueueworkertaskadditionalfieldprovider' => $extensionPath . 'Scheduler/IndexQueueWorkerTaskAdditionalFieldProvider.php',
	'Tx_Solr_Scheduler_Reindextask' => $extensionPath . 'Scheduler/ReIndexTask.php',
	'Tx_Solr_Scheduler_Reindextaskadditionalfieldprovider' => $extensionPath . 'Scheduler/ReIndexTaskAdditionalFieldProvider.php',

	// reports

	'Tx_Solr_Report_AccessFilterPluginInstalledStatus' => $extensionPath . 'Report/AccessFilterPluginInstalledStatus.php',
	'Tx_Solr_Report_AllowUrlFOpenStatus' => $extensionPath . 'Report/AllowUrlFOpenStatus.php',
	'Tx_Solr_Report_FilterVarStatus' => $extensionPath . 'Report/FilterVarStatus.php',
	'Tx_Solr_Report_IndexReport' => $extensionPath . 'Report/IndexReport.php',
	'Tx_Solr_Report_SchemaStatus' => $extensionPath . 'Report/SchemaStatus.php',
	'Tx_Solr_Report_SolrConfigStatus' => $extensionPath . 'Report/SolrConfigStatus.php',
	'Tx_Solr_Report_SolrConfigurationStatus' => $extensionPath . 'Report/SolrConfigurationStatus.php',
	'Tx_Solr_Report_SolrStatus' => $extensionPath . 'Report/SolrStatus.php',
	'Tx_Solr_Report_SolrVersionStatus' => $extensionPath . 'Report/SolrVersionStatus.php',

	// interfaces

	'Tx_Solr_Additionalindexqueueitemindexer' => $extensionPath . 'Interfaces/AdditionalIndexQueueItemIndexer.php',
	'Tx_Solr_Additionalpageindexer' => $extensionPath . 'Interfaces/AdditionalPageIndexer.php',
	'Tx_Solr_Commandpluginaware' => $extensionPath . 'Interfaces/CommandPluginAware.php',
	'Tx_Solr_Commandpostprocessor' => $extensionPath . 'Interfaces/CommandPostProcessor.php',
	'Tx_Solr_Errordetector' => $extensionPath . 'Interfaces/ErrorDetector.php',
	'Tx_Solr_Facetoptionsrenderer' => $extensionPath . 'Interfaces/FacetOptionsRenderer.php',
	'Tx_Solr_Facetrenderer' => $extensionPath . 'Interfaces/FacetRenderer.php',
	'Tx_Solr_Facetsmodifier' =>  $extensionPath . 'Interfaces/FacetsModifier.php',
	'Tx_Solr_Fieldprocessor' => $extensionPath . 'Interfaces/FieldProcessor.php',
	'Tx_Solr_Formmodifier' => $extensionPath . 'Interfaces/FormModifier.php',
	'Tx_Solr_Garbagecollectorpostprocessor' => $extensionPath . 'Interfaces/GarbageCollectorPostProcessor.php',
	'Tx_Solr_Indexqueueinitializationpostprocessor' => $extensionPath . 'Interfaces/IndexQueueInitializationPostProcessor.php',
	'Tx_Solr_Indexqueueinitializer' => $extensionPath . 'Interfaces/IndexQueueInitializer.php',
	'Tx_Solr_Indexqueuepageindexerdataurlmodifier' => $extensionPath . 'Interfaces/IndexQueuePageIndexerDataUrlModifier.php',
	'Tx_Solr_Indexqueuepageindexerdocumentsmodifier' => $extensionPath . 'Interfaces/IndexQueuePageIndexerDocumentsModifier.php',
	'Tx_Solr_Indexqueuepageindexerfrontendhelper' => $extensionPath . 'Interfaces/IndexQueuePageIndexerFrontendHelper.php',
	'Tx_Solr_Pagedocumentpostprocessor' => $extensionPath . 'Interfaces/PageDocumentPostProcessor.php',
	'Tx_Solr_Pluginaware' => $extensionPath . 'Interfaces/PluginAware.php',
	'Tx_Solr_Plugincommand' => $extensionPath . 'Interfaces/PluginCommand.php',
	'Tx_Solr_Queryaware' => $extensionPath . 'Interfaces/QueryAware.php',
	'Tx_Solr_Queryfacetbuilder' => $extensionPath . 'Interfaces/QueryFacetBuilder.php',
	'Tx_Solr_Queryfilterencoder' => $extensionPath . 'Interfaces/QueryFilterEncoder.php',
	'Tx_Solr_Querymodifier' => $extensionPath . 'Interfaces/QueryModifier.php',
	'Tx_Solr_Responsemodifier' => $extensionPath . 'Interfaces/ResponseModifier.php',
	'Tx_Solr_Responseprocessor' => $extensionPath . 'Interfaces/ResponseProcessor.php',
	'Tx_Solr_Resultdocumentmodifier' => $extensionPath . 'Interfaces/ResultDocumentModifier.php',
	'Tx_Solr_Resultsetmodifier' => $extensionPath . 'Interfaces/ResultSetModifier.php',
	'Tx_Solr_Searchaware' => $extensionPath . 'Interfaces/SearchAware.php',
	'Tx_Solr_Searchcomponent' => $extensionPath . 'Interfaces/SearchComponent.php',
	'Tx_Solr_Serializedvaluedetector' => $extensionPath . 'Interfaces/SerializedValueDetector.php',
	'Tx_Solr_Subpartviewhelper' => $extensionPath . 'Interfaces/SubpartViewHelper.php',
	'Tx_Solr_Substitutepageindexer' => $extensionPath . 'Interfaces/SubstitutePageIndexer.php',
	'Tx_Solr_Templatemodifier' => $extensionPath . 'Interfaces/TemplateModifier.php',
	'Tx_Solr_Viewhelper' => $extensionPath . 'Interfaces/ViewHelper.php',
	'Tx_Solr_Viewhelperprovider' => $extensionPath . 'Interfaces/ViewHelperProvider.php',
);
?>
